services:
  backend:
    build: ./backend
    user: 1000:1000
    volumes:
      - ./backend/db.sqlite3:/backend/db.sqlite3 # persist SQLite DB
    environment:
      - TZ=Asia/Singapore
    ports:
      - "8000:8000" # expose backend port
    restart: always

  frontend:
    build: ./frontend
    user: 1000:1000
    ports:
      - "10000:3000"
    environment:
      - TZ=Asia/Singapore
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    restart: always
