# Generated by Django 4.1.5 on 2023-01-29 13:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-completed_date", "due_date", "start_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("img_url", models.URLField(blank=True, max_length=400)),
                ("product_url", models.URLField(blank=True, max_length=400)),
                ("count", models.IntegerField(default=0, null=True)),
                ("repeat", models.BooleanField(default=False)),
                ("last_purchased_date", models.DateField(blank=True, null=True)),
                ("tags", models.ManyToManyField(blank=True, to="todos.tag")),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "DAILY"),
                            ("WEEKLY", "WEEKLY"),
                            ("MONTHLY", "MONTHLY"),
                            ("QUARTERLY", "QUARTERLY"),
                            ("YEARLY", "YEARLY"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "effort",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=6),
                ),
                (
                    "reward",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=6),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="todos.project",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="todos.tag")),
            ],
            options={
                "ordering": ["-completed_date", "due_date", "start_date"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="todos.tag"),
        ),
    ]
